// This is an autogenerated file from Firebase Studio.
/**
 * @file src/ai/flows/listing-optimizer.ts
 * @fileOverview يوفر هذا الملف وظيفة Genkit flow لتحسين قوائم المنتجات باستخدام الذكاء الاصطناعي.
 * 
 * يحتوي الملف على:
 * - `optimizeListing`: دالة مُصدَّرة تستدعي `optimizeListingFlow` لتقديم اقتراحات لتحسين وصف المنتج.
 * - `OptimizeListingInputSchema` و `OptimizeListingInput`: تعريف مخطط ونوع بيانات الإدخال لـ flow، والذي يتضمن وصف المنتج الحالي.
 * - `OptimizeListingOutputSchema` و `OptimizeListingOutput`: تعريف مخطط ونوع بيانات الإخراج لـ flow، والذي يتضمن قائمة بالعبارات المقترحة.
 * - `prompt`: كائن `ai.definePrompt` الذي يحدد مطالبة (prompt) لنموذج اللغة الكبير (LLM) بناءً على وصف المنتج.
 * - `optimizeListingFlow`: كائن `ai.defineFlow` الذي يغلف المطالبة وينفذها، معالجًا المدخلات والمخرجات.
 * 
 * آلية العمل:
 * 1. يستقبل `optimizeListingFlow` وصف منتج كإدخال.
 * 2. يقوم بتمرير هذا الوصف إلى `prompt` المعرّف.
 * 3. يستخدم `prompt` نموذج اللغة ليقوم بإنشاء 5 عبارات مقترحة لتحسين القائمة، مع التركيز على الميزات واللغة الجذابة.
 * 4. يعيد `optimizeListingFlow` قائمة العبارات المقترحة.
 * 
 * يتم استخدام 'use server'; للإشارة إلى أن هذا الكود يمكن تشغيله على الخادم.
 */
'use server';

/**
 * @fileOverview Provides AI-powered suggestions based on product descriptions to enhance listings.
 *
 * - optimizeListing - A function that suggests improvements for product listings.
 * - OptimizeListingInput - The input type for the optimizeListing function.
 * - OptimizeListingOutput - The return type for the optimizeListing function.
 */

import {ai} from '@/ai/genkit'; // استيراد كائن Genkit المهيأ
import {z} from 'genkit'; // استيراد Zod من Genkit لتعريف المخططات

// تعريف مخطط Zod لبيانات الإدخال
const OptimizeListingInputSchema = z.object({
  productDescription: z
    .string()
    .describe('The current description of the product listing.'), // وصف المنتج الحالي
});
// تعريف نوع TypeScript المقابل لبيانات الإدخال
export type OptimizeListingInput = z.infer<typeof OptimizeListingInputSchema>;

// تعريف مخطط Zod لبيانات الإخراج
const OptimizeListingOutputSchema = z.object({
  suggestedPhrases: z
    .array(z.string()) // مصفوفة من السلاسل النصية
    .describe('A list of suggested phrases to enhance the product listing.'), // قائمة بالعبارات المقترحة
});
// تعريف نوع TypeScript المقابل لبيانات الإخراج
export type OptimizeListingOutput = z.infer<typeof OptimizeListingOutputSchema>;

/**
 * @function optimizeListing
 * @description دالة مساعدة مُصدَّرة لاستدعاء `optimizeListingFlow`.
 * @param {OptimizeListingInput} input - بيانات الإدخال التي تحتوي على وصف المنتج.
 * @returns {Promise<OptimizeListingOutput>} - وعد يحتوي على قائمة العبارات المقترحة.
 */
export async function optimizeListing(input: OptimizeListingInput): Promise<OptimizeListingOutput> {
  return optimizeListingFlow(input);
}

// تعريف المطالبة (Prompt) لنموذج اللغة
const prompt = ai.definePrompt({
  name: 'optimizeListingPrompt', // اسم المطالبة
  input: {schema: OptimizeListingInputSchema}, // مخطط بيانات الإدخال
  output: {schema: OptimizeListingOutputSchema}, // مخطط بيانات الإخراج (لتوجيه النموذج لتوليد مخرجات متوافقة)
  // نص المطالبة الفعلي باستخدام Handlebars لدمج وصف المنتج
  prompt: `You are an expert marketing copywriter specializing in writing product descriptions for a wedding rental and sales shop called StyleEase.

  Given the following product description, suggest phrases to enhance the listing and make it more attractive to customers. Provide 5 suggested phrases.

  Product Description: {{{productDescription}}}

  The phrases should:
  - Highlight key features and benefits.
  - Use descriptive and engaging language.
  - Appeal to customers looking for wedding attire.
  - Be concise and ready to use in a product listing.
  `,
});

// تعريف Genkit Flow
const optimizeListingFlow = ai.defineFlow(
  {
    name: 'optimizeListingFlow', // اسم الـ Flow
    inputSchema: OptimizeListingInputSchema, // مخطط بيانات الإدخال للـ Flow
    outputSchema: OptimizeListingOutputSchema, // مخطط بيانات الإخراج للـ Flow
  },
  async input => { // الدالة التي يتم تنفيذها عند استدعاء الـ Flow
    // استدعاء المطالبة (prompt) مع بيانات الإدخال
    const {output} = await prompt(input);
    // إرجاع المخرجات من المطالبة (يجب أن تكون متوافقة مع OptimizeListingOutputSchema)
    return output!; 
  }
);
